name: Scheduled Webhook

#on:
  #schedule:
    #- cron: "*/5* * * *"
  #workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: |
          curl -X POST https://waha-74hs.onrender.com/ \
            -H "Content-Type: application/json" \
            -d '{
              "type": "health",
              "time": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }'